# Generated by Django 4.2.20 on 2025-04-30 14:55

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(help_text='برای استفاده در URLها، معمولا نسخه لاتین و خط\u200cفاصله\u200cدار نام است.', max_length=110, unique=True, verbose_name='اسلاگ (نامک)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='اگر خالی باشد، تخفیف به صورت خودکار اعمال می\u200cشود (مثلا برای یک سانس خاص).', max_length=50, null=True, unique=True, verbose_name='کد تخفیف')),
                ('description', models.CharField(max_length=255, verbose_name='توضیحات تخفیف')),
                ('discount_type', models.CharField(choices=[('P', 'درصدی'), ('F', 'مبلغ ثابت')], max_length=1, verbose_name='نوع تخفیف')),
                ('value', models.DecimalField(decimal_places=2, help_text='اگر درصدی است عدد بین 0 تا 100، اگر ثابت است مبلغ به تومان', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='مقدار تخفیف')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='حداکثر مبلغ تخفیف (برای نوع درصدی)')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع اعتبار')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان اعتبار')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='محدودیت تعداد استفاده')),
                ('used_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='تعداد استفاده شده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیف\u200cها',
            },
        ),
        migrations.CreateModel(
            name='OptionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام آپشن')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='قیمت آپشن')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات آپشن')),
            ],
            options={
                'verbose_name': 'آپشن انتخابی',
                'verbose_name_plural': 'آپشن\u200cهای انتخابی',
            },
        ),
        migrations.CreateModel(
            name='SportFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام سالن')),
                ('description', models.TextField(verbose_name='توضیحات کامل')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('gender_type', models.CharField(choices=[('M', 'آقایان'), ('F', 'بانوان'), ('B', 'آقایان و بانوان (مشترک یا سانس\u200cهای جداگانه)')], default='B', max_length=1, verbose_name='مخصوص')),
                ('is_active', models.BooleanField(default=True, help_text='آیا این سالن برای رزرو نمایش داده شود؟', verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facilities', to='provider.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'سالن ورزشی',
                'verbose_name_plural': 'سالن\u200cهای ورزشی',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام تگ')),
                ('slug', models.SlugField(max_length=110, unique=True, verbose_name='اسلاگ (نامک)')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('start_time', models.TimeField(verbose_name='زمان شروع')),
                ('end_time', models.TimeField(verbose_name='زمان پایان')),
                ('base_price', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='قیمت پایه')),
                ('is_available', models.BooleanField(default=True, verbose_name='در دسترس برای رزرو')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_slots', to='provider.discount', verbose_name='تخفیف اختصاصی سانس')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='provider.sportfacility', verbose_name='سالن ورزشی')),
            ],
            options={
                'verbose_name': 'سانس (نوبت زمانی)',
                'verbose_name_plural': 'سانس\u200cها',
                'ordering': ['date', 'start_time'],
                'unique_together': {('facility', 'date', 'start_time')},
            },
        ),
        migrations.AddField(
            model_name='sportfacility',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='facilities', to='provider.tag', verbose_name='تگ\u200cها'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'در انتظار پرداخت'), ('C', 'تایید شده'), ('X', 'لغو شده'), ('E', 'منقضی شده')], default='P', max_length=1, verbose_name='وضعیت رزرو')),
                ('final_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ نهایی پرداخت شده/پرداختنی')),
                ('applied_discount_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد تخفیف استفاده شده')),
                ('reservation_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت رزرو')),
                ('payment_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت کاربر')),
                ('selected_optional_services', models.ManyToManyField(blank=True, related_name='reservations', to='provider.optionalservice', verbose_name='آپشن\u200cهای انتخابی رزرو')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='provider.timeslot', verbose_name='سانس رزرو شده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزروها',
                'ordering': ['-reservation_time'],
            },
        ),
        migrations.AddField(
            model_name='optionalservice',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optional_services', to='provider.sportfacility', verbose_name='سالن ورزشی'),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='متن ویژگی')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='provider.sportfacility', verbose_name='سالن ورزشی')),
            ],
            options={
                'verbose_name': 'ویژگی مثبت (امکانات)',
                'verbose_name_plural': 'ویژگی\u200cهای مثبت (امکانات)',
            },
        ),
        migrations.CreateModel(
            name='FacilityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='facility_images/', verbose_name='تصویر')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان تصویر')),
                ('is_cover', models.BooleanField(default=False, help_text='آیا این تصویر اصلی سالن است؟', verbose_name='تصویر کاور')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='provider.sportfacility', verbose_name='سالن ورزشی')),
            ],
            options={
                'verbose_name': 'تصویر سالن',
                'verbose_name_plural': 'گالری تصاویر سالن',
                'ordering': ['-is_cover', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Drawback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='متن عیب')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawbacks', to='provider.sportfacility', verbose_name='سالن ورزشی')),
            ],
            options={
                'verbose_name': 'ویژگی منفی (عیب)',
                'verbose_name_plural': 'ویژگی\u200cهای منفی (معایب)',
            },
        ),
        migrations.AlterUniqueTogether(
            name='optionalservice',
            unique_together={('facility', 'name')},
        ),
    ]
