# Generated by Django 4.2.20 on 2025-04-30 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_remove_city_name_fa_remove_province_name_fa'),
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityimage',
            name='uploaded_by',
            field=models.CharField(choices=[('admin', 'ادمین'), ('user', 'کاربر')], default='admin', max_length=50, verbose_name='��پلود شده بوسیله'),
        ),
        migrations.AddField(
            model_name='sportfacility',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='address.city', verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='sportfacility',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='address.province', verbose_name='ا��تان'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='gender_type',
            field=models.CharField(choices=[('M', 'آقایان'), ('F', 'بانوان')], default='B', max_length=1, verbose_name='مخصوص'),
        ),
        migrations.AlterField(
            model_name='sportfacility',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='sportfacility',
            name='gender_type',
            field=models.CharField(choices=[('M', 'آقایان'), ('F', 'بانوان'), ('B', 'آقایان و بانوان (مشترک با سانس\u200cهای جداگانه)')], default='B', max_length=1, verbose_name='مخصوص'),
        ),
    ]
