# Generated by Django 4.2.20 on 2025-05-01 17:47

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_alter_address_options_alter_city_options_and_more'),
        ('provider', '0002_facilityimage_uploaded_by_sportfacility_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='متن جایگزین تصویر'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='end_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ پایان اعتبار'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='start_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ شروع اعتبار'),
        ),
        migrations.AlterField(
            model_name='facilityimage',
            name='uploaded_by',
            field=models.CharField(choices=[('admin', 'ادمین'), ('user', 'کاربر')], default='admin', max_length=50, verbose_name='آپلود شده بوسیله'),
        ),
        migrations.AlterField(
            model_name='sportfacility',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='address.province', verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ'),
        ),
    ]
