# Generated by Django 4.2.20 on 2025-04-30 14:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('name_fa', models.CharField(blank=True, max_length=60, null=True)),
                ('slug', models.CharField(max_length=60)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.CharField(max_length=60)),
                ('name_fa', models.CharField(blank=True, max_length=60, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.province')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Address Field')),
                ('phone', models.CharField(max_length=11, verbose_name='phone number')),
                ('zipcode', models.CharField(blank=True, max_length=12, null=True, verbose_name='zip code')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='address.city')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='address.province')),
            ],
        ),
    ]
