# Generated by Django 4.2.20 on 2025-04-30 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='name_fa',
        ),
        migrations.RemoveField(
            model_name='province',
            name='name_fa',
        ),
    ]
