# Generated by Django 4.2.20 on 2025-05-01 17:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_remove_city_name_fa_remove_province_name_fa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'شهر', 'verbose_name_plural': 'شهرها'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'استان', 'verbose_name_plural': 'استان\u200cها'},
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=100, verbose_name='آدرس کامل'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='address.city', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='address.province', verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='city',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='city',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='طول جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=60, verbose_name='نام شهر'),
        ),
        migrations.AlterField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.province', verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.CharField(max_length=60, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='city',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='شناسه یکتا'),
        ),
        migrations.AlterField(
            model_name='province',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='province',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='طول جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=60, verbose_name='نام استان'),
        ),
        migrations.AlterField(
            model_name='province',
            name='slug',
            field=models.CharField(max_length=60, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='province',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='شناسه یکتا'),
        ),
    ]
